version: '3.9'
services:

  postgres:
    container_name: postgres
    network_mode: host
    image: postgres
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'postgres'
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data


  mongodb:
    container_name: mongodb
    network_mode: host
    image : mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_DATABASE=authService
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - .data/db:/data/db

  redis:
    container_name: redis
    image: redis:alpine
    network_mode: host
    command: redis-server --requirepass secret
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: app
    image: app
    environment:
      PG_URL: 'postgres://user:pass@postgres:5432/postgres'
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongodb
      - redis

volumes:
  pg-data:
