app:
  name: 'go-auth-service'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'go-auth-service-template'

postgres:
  pool_max: 2

jwt:
  access_token_ttl: 15m
  refresh_token_ttl: 30m
  signing_key: 'secret'