app:
  name: 'go-auth-service'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'go-auth-service'

postgres:
  pool_max: 2

mongodb:
  database: 'authService'

cache:
  ttl: 1m

auth:
  github_client_id: '4965a8fd3a9df8f0f405'
  github_scope: 'read:user,user:email'

  google_client_id: '5kj6h7g89f0d23412123'
  google_scope: 'user'

session:
  ttl: 60m
  cookie_key: 'id'
  cookie_domain: ''
  cookie_secure: false
  cookie_httponly: true

access_token:
  ttl: 1m
  signing_key: 'secret'
