app:
  name: 'go-auth-service'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'go-auth-service-template'

postgres:
  pool_max: 2

mongodb:
  database: 'authService'

cache:
  ttl: 1m

session:
  ttl: 60m
  cookie_key: 'id'
  cookie_domain: ''
  cookie_secure: false
  cookie_httponly: true

jwt:
  ttl: 1m
  signing_key: 'secret'
