basePath: /api/v1
definitions:
  domain.Translation:
    properties:
      destination:
        example: en
        type: string
      original:
        example: текст для перевода
        type: string
      source:
        example: auto
        type: string
      translation:
        example: text for translation
        type: string
    type: object
  domain.User:
    properties:
      created_at:
        example: "2009-11-10 23:00:00"
        type: string
      email:
        example: email@gmail.com
        type: string
      first_name:
        example: Alex
        type: string
      id:
        example: 1
        type: integer
      last_name:
        example: Malone
        type: string
      password:
        example: secret
        type: string
    required:
    - created_at
    - email
    - password
    type: object
  v1.createUserRequest:
    properties:
      email:
        example: user@mail.com
        type: string
      password:
        example: secret
        type: string
    required:
    - email
    - password
    type: object
  v1.doTranslateRequest:
    properties:
      destination:
        example: en
        type: string
      original:
        example: текст для перевода
        type: string
      source:
        example: auto
        type: string
    required:
    - destination
    - original
    - source
    type: object
  v1.historyResponse:
    properties:
      history:
        items:
          $ref: '#/definitions/domain.Translation'
        type: array
    type: object
  v1.response:
    properties:
      error:
        example: message
        type: string
    type: object
host: 0.0.0.0:8080
info:
  contact: {}
  description: REST API authentication service
  title: Golang auth service
  version: "1.0"
paths:
  /translation/do-translate:
    post:
      consumes:
      - application/json
      description: Translate a text
      operationId: do-translate
      parameters:
      - description: Set up translation
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.doTranslateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Translation'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
      summary: Translate
      tags:
      - translation
  /translation/history:
    get:
      consumes:
      - application/json
      description: Show all translation history
      operationId: history
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.historyResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
      summary: Show history
      tags:
      - translation
  /users/create:
    post:
      consumes:
      - application/json
      description: Register a new user
      operationId: create
      parameters:
      - description: Register a new user
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.createUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
      summary: Create
      tags:
      - create
swagger: "2.0"
