basePath: /api/v1
definitions:
  domain.ArchiveUserRequest:
    properties:
      is_archive:
        example: false
        type: boolean
    required:
    - is_archive
    type: object
  domain.CreateUserRequest:
    properties:
      confirm_password:
        example: secret
        type: string
      email:
        example: user@mail.com
        type: string
      password:
        example: secret
        type: string
    required:
    - confirm_password
    - email
    - password
    type: object
  domain.UpdateUserRequest:
    properties:
      first_name:
        example: Alex
        type: string
      last_name:
        example: Malykh
        type: string
      username:
        example: username
        type: string
    type: object
  domain.User:
    properties:
      created_at:
        example: "2021-08-31T16:55:18.080768Z"
        type: string
      email:
        example: user@mail.com
        type: string
      first_name:
        example: Alex
        type: string
      id:
        example: 1
        type: integer
      is_active:
        example: true
        type: boolean
      is_archive:
        example: false
        type: boolean
      last_name:
        example: Malykh
        type: string
      updated_at:
        example: "2021-08-31T16:55:18.080768Z"
        type: string
      username:
        example: username
        type: string
    type: object
  v1.messageResponse:
    properties:
      error:
        example: message
        type: string
    type: object
  v1.validationErrorResponse:
    properties:
      error:
        additionalProperties:
          type: string
        example:
          ModelName.FieldName: validation error message
        type: object
    type: object
host: 0.0.0.0:8080
info:
  contact: {}
  description: REST API authentication service
  title: Golang auth service
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      description: Register a new user with email and password
      operationId: signup
      parameters:
      - description: To register a new user email and password should be provided
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.messageResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/v1.validationErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.messageResponse'
      summary: Sign Up
      tags:
      - Users
  /users/{id}:
    patch:
      consumes:
      - application/json
      description: Update user data partially
      operationId: partialUpdate
      parameters:
      - description: Provide at least one user field to update user data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.UpdateUserRequest'
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.messageResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/v1.validationErrorResponse'
      summary: Partial Update
      tags:
      - Users
  /users/{id}/archive:
    patch:
      consumes:
      - application/json
      description: Archive/restore user
      operationId: archive
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: To archive/restore user is_archive boolean should be provided
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.ArchiveUserRequest'
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.messageResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/v1.validationErrorResponse'
      summary: Archive user
      tags:
      - Users
swagger: "2.0"
