basePath: /api/v1
definitions:
  v1.createUserRequest:
    properties:
      email:
        example: user@mail.com
        type: string
      password:
        example: secret
        type: string
    required:
    - email
    - password
    type: object
  v1.createUserResponse:
    properties:
      created_at:
        example: "2021-08-31T16:55:18.080768Z"
        type: string
      email:
        example: user@mail.com
        type: string
      id:
        type: integer
    type: object
  v1.messageResponse:
    properties:
      error:
        example: message
        type: string
    type: object
  v1.validationErrorResponse:
    properties:
      error:
        additionalProperties:
          type: string
        example:
          email: must be a valid email address
          password: must be at least 6 characters in length
        type: object
    type: object
host: 0.0.0.0:8080
info:
  contact: {}
  description: REST API authentication service
  title: Golang auth service
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      description: Register a new user
      operationId: create
      parameters:
      - description: Register a new user
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.createUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.createUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.messageResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/v1.validationErrorResponse'
      summary: Create
      tags:
      - Users
swagger: "2.0"
